import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "@/components/ui/sonner";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { Youtube, Loader2, ChevronDown, ChevronUp, RotateCcw, Download } from "lucide-react";
import { useEffect } from "react";

interface Flashcard {
  front: string;
  back: string;
}

interface TutorYouTubeProps {
  initialState?: { url: string; flashcards?: Flashcard[] };
  onSave: (state: { url: string; flashcards?: Flashcard[] }) => void;
}

export function TutorYouTube({ initialState, onSave }: TutorYouTubeProps) {
  const { refresh } = useAuth();
  const [url, setUrl] = useState(initialState?.url || "");
  const [loading, setLoading] = useState(false);
  const [flashcards, setFlashcards] = useState<Flashcard[]>(Array.isArray(initialState?.flashcards) ? initialState.flashcards : []);
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  useEffect(() => {
    if (initialState) {
      setUrl(initialState.url || "");
      setFlashcards(Array.isArray(initialState.flashcards) ? initialState.flashcards : []);
    }
  }, [initialState]);

  const generateFlashcards = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!url.trim()) return toast.error("Please enter a YouTube URL.");
    
    setLoading(true);
    
    try {
      const res = await api<{ message: string, flashcards: Flashcard[] }>("/api/tutor/youtube", {
        method: "POST",
        body: { url }
      });
      
      const cards = res.flashcards || [];
      setFlashcards(cards);
      onSave({ url, flashcards: cards });
      toast.success(`Generated ${cards.length} flashcards!`);
    } catch (err: any) {
      toast.error(err.message || "Failed to generate flashcards from video");
    } finally {
      setLoading(false);
      refresh().catch(console.error);
    }
  };

  const resetForm = () => {
    setUrl("");
    setFlashcards([]);
    setExpandedIndex(null);
    onSave({ url: "", flashcards: [] });
  };

  const downloadAsHtml = () => {
    const cardsHtml = flashcards.map((fc, i) => `
      <div class="card">
        <div class="card-number">#${i + 1}</div>
        <div class="card-front"><span class="label">Q:</span> ${fc.front}</div>
        <div class="card-back"><span class="label">A:</span> ${fc.back}</div>
      </div>`).join("");

    const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>GraspAI — YouTube Flashcards</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#f5f0e8;color:#3d2e1f;padding:40px 20px}
.header{text-align:center;margin-bottom:40px}
.header h1{font-size:28px;color:#5c3d2e;margin-bottom:8px}
.header p{color:#8b7355;font-size:14px}
.cards{max-width:800px;margin:0 auto;display:flex;flex-direction:column;gap:16px}
.card{background:#fff;border-radius:12px;padding:24px;box-shadow:0 2px 8px rgba(0,0,0,.08);border-left:4px solid #8b6914;position:relative}
.card-number{position:absolute;top:12px;right:16px;font-size:12px;color:#b8a080;font-weight:600}
.card-front{font-size:16px;font-weight:600;margin-bottom:12px;padding-bottom:12px;border-bottom:1px solid #e8dfd3}
.card-back{font-size:14px;color:#5c4a3a;line-height:1.6}
.label{font-weight:700;color:#8b6914;margin-right:4px}
.footer{text-align:center;margin-top:40px;color:#b8a080;font-size:12px}
@media print{body{background:#fff;padding:20px}.card{box-shadow:none;border:1px solid #ddd;break-inside:avoid}}
</style></head><body>
<div class="header"><h1>☕ GraspAI — YouTube Flashcards</h1><p>${flashcards.length} flashcards generated from your video</p></div>
<div class="cards">${cardsHtml}</div>
<div class="footer">Generated by GraspAI — Study, brewed.</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "flashcards.html";
    a.click();
    URL.revokeObjectURL(a.href);
    toast.success("Flashcards downloaded!");
  };

  return (
    <Card className="flex flex-col flex-1 min-h-0 overflow-hidden border-border bg-card mt-0">
      <CardContent className="flex flex-col flex-1 p-4 sm:p-6 overflow-hidden relative space-y-4">
        
        {flashcards.length === 0 ? (
          <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground opacity-60 min-h-0">
            <Youtube className="h-12 w-12 mb-4" />
            <p className="text-sm font-medium">Turn any Lecture into Flashcards</p>
            <p className="text-xs mt-1 text-center max-w-xs">Paste a YouTube video link below. The AI will extract the transcript, summarize key concepts, and generate interactive flashcards for you.</p>
          </div>
        ) : (
          <div className="flex-1 overflow-auto space-y-3 min-h-0">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-sm font-semibold">{flashcards.length} Flashcards Generated</h3>
              <div className="flex gap-1">
                <Button variant="ghost" size="sm" onClick={downloadAsHtml} className="text-xs text-muted-foreground hover:text-foreground">
                  <Download className="h-3 w-3 mr-1" /> Download
                </Button>
                <Button variant="ghost" size="sm" onClick={resetForm} className="text-xs text-muted-foreground hover:text-destructive">
                  <RotateCcw className="h-3 w-3 mr-1" /> Reset
                </Button>
              </div>
            </div>
            {flashcards.map((fc, i) => (
              <div
                key={i}
                className="border border-border rounded-lg bg-muted/30 overflow-hidden transition-all"
              >
                <button
                  className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-muted/50 transition"
                  onClick={() => setExpandedIndex(expandedIndex === i ? null : i)}
                >
                  <span className="text-sm font-medium pr-4">{fc.front}</span>
                  {expandedIndex === i ? (
                    <ChevronUp className="h-4 w-4 text-muted-foreground shrink-0" />
                  ) : (
                    <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" />
                  )}
                </button>
                {expandedIndex === i && (
                  <div className="px-4 py-3 border-t border-border bg-background text-sm text-muted-foreground">
                    {fc.back}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        <div className="shrink-0 pt-2 border-t border-border flex flex-col gap-2">
          <form onSubmit={generateFlashcards} className="flex items-center gap-2">
            <Input 
              placeholder="https://www.youtube.com/watch?v=..." 
              value={url} 
              onChange={(e) => setUrl(e.target.value)} 
              disabled={loading || flashcards.length > 0}
              className="flex-1"
            />

            {flashcards.length === 0 && (
              <Button type="submit" disabled={loading || !url.trim()}>
                {loading && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
                Generate
              </Button>
            )}
          </form>
          <div className="text-[10px] sm:text-xs text-muted-foreground">
            Each generation costs 1 credit. Takes up to 30 seconds for long videos.
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
