/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppStudyRouteImport } from './routes/app.study'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as LegalTermsRouteImport } from './routes/_legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/_legal.privacy'
import { Route as LegalLicenseRouteImport } from './routes/_legal.license'
import { Route as LegalFaqRouteImport } from './routes/_legal.faq'
import { Route as LegalCookiesRouteImport } from './routes/_legal.cookies'
import { Route as LegalAboutRouteImport } from './routes/_legal.about'
import { Route as AppSessionsSessionIdIndexRouteImport } from './routes/app.sessions.$sessionId.index'
import { Route as AppSessionsSessionIdPastPapersRouteImport } from './routes/app.sessions.$sessionId.past-papers'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalLicenseRoute = LegalLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalFaqRoute = LegalFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LegalRoute,
} as any)
const AppSessionsSessionIdIndexRoute =
  AppSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSessionsSessionIdPastPapersRoute =
  AppSessionsSessionIdPastPapersRouteImport.update({
    id: '/sessions/$sessionId/past-papers',
    path: '/sessions/$sessionId/past-papers',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/about': typeof LegalAboutRoute
  '/cookies': typeof LegalCookiesRoute
  '/faq': typeof LegalFaqRoute
  '/license': typeof LegalLicenseRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/sessions/$sessionId/past-papers': typeof AppSessionsSessionIdPastPapersRoute
  '/app/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LegalAboutRoute
  '/cookies': typeof LegalCookiesRoute
  '/faq': typeof LegalFaqRoute
  '/license': typeof LegalLicenseRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/sessions/$sessionId/past-papers': typeof AppSessionsSessionIdPastPapersRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_legal': typeof LegalRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_legal/about': typeof LegalAboutRoute
  '/_legal/cookies': typeof LegalCookiesRoute
  '/_legal/faq': typeof LegalFaqRoute
  '/_legal/license': typeof LegalLicenseRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/sessions/$sessionId/past-papers': typeof AppSessionsSessionIdPastPapersRoute
  '/app/sessions/$sessionId/': typeof AppSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/cookies'
    | '/faq'
    | '/license'
    | '/privacy'
    | '/terms'
    | '/app/dashboard'
    | '/app/study'
    | '/app/tutor'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/sessions/$sessionId/past-papers'
    | '/app/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cookies'
    | '/faq'
    | '/license'
    | '/privacy'
    | '/terms'
    | '/app/dashboard'
    | '/app/study'
    | '/app/tutor'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/sessions/$sessionId/past-papers'
    | '/app/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_legal'
    | '/app'
    | '/_legal/about'
    | '/_legal/cookies'
    | '/_legal/faq'
    | '/_legal/license'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/app/dashboard'
    | '/app/study'
    | '/app/tutor'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/sessions/$sessionId/past-papers'
    | '/app/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study': {
      id: '/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/license': {
      id: '/_legal/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LegalLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/faq': {
      id: '/_legal/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LegalFaqRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/cookies': {
      id: '/_legal/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/about': {
      id: '/_legal/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof LegalRoute
    }
    '/app/sessions/$sessionId/': {
      id: '/app/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId/'
      preLoaderRoute: typeof AppSessionsSessionIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sessions/$sessionId/past-papers': {
      id: '/app/sessions/$sessionId/past-papers'
      path: '/sessions/$sessionId/past-papers'
      fullPath: '/app/sessions/$sessionId/past-papers'
      preLoaderRoute: typeof AppSessionsSessionIdPastPapersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface LegalRouteChildren {
  LegalAboutRoute: typeof LegalAboutRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalFaqRoute: typeof LegalFaqRoute
  LegalLicenseRoute: typeof LegalLicenseRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAboutRoute: LegalAboutRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalFaqRoute: LegalFaqRoute,
  LegalLicenseRoute: LegalLicenseRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppStudyRoute: typeof AppStudyRoute
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionsSessionIdPastPapersRoute: typeof AppSessionsSessionIdPastPapersRoute
  AppSessionsSessionIdIndexRoute: typeof AppSessionsSessionIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppStudyRoute: AppStudyRoute,
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionsSessionIdPastPapersRoute: AppSessionsSessionIdPastPapersRoute,
  AppSessionsSessionIdIndexRoute: AppSessionsSessionIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
